{% set version = "0.1.13" %}

package:
  name: stockpy-learn
  version: {{ version }}

source:
  git_url: https://github.com/SilvioBaratto/stockpy.git
  git_tag: v{{ version }}

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pytorch >=1.9.0
    - pyro-ppl >=1.7.0
    - numpy >=1.20.0

about:
  home: https://github.com/SilvioBaratto/stockpy
  license: MIT
  summary: Machine Learning library to make stock market prediction